### ISSUE TITLE
Mover alpha.onodo.org a onodo.org para el lanzamiento

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/onodo#261]

**Comment by esebastian** [comment]
Respecto al último punto, no veo problema. Desde el punto de vista de la aplicación no debería ser un problema que se acceda por más de un nombre de dominio, pero desde el punto de vista del usuario puede ser más interesante tener una única referencia.

**Comment by dcabo** [comment]
Yo no sé prácticamente nada de SEO ni historias, pero algunas herramientas de Google (Webmaster, Analytics) a veces recomiendan que no haya más de una URL para lo mismo, así que si lo metemos todo en onodo.org pues casi mejor, sí. Yo propongo sin la www porque creo que no aporta nada, pero si alguien opina que es mejor que lo canónico sea con www no tengo problema.

**Comment by esebastian** [comment]
El tema con el _bare domain_ es que dependiendo del proveedor de DNS puede ser más fácil o más difícil configurar una CDN o un balanceador, porque lo que se suele necesitar es un CNAME y no todos los DNS lo soportan en los _bare_.

**Comment by dcabo** [comment]
Pues con www, no tengo una opinión fuerte sobre el tema.

**Comment by rauldiazpoblete** [comment]
Yo creo que tenemos que usar la url sin www porque es como lo hemos estado moviendo en redes sociales y como aparece en toda nuestra variada gama de artículos de merchandising de Onodo

**Comment by dcabo** [comment]
Parece haber preferencia generalizada por onodo.org, y a mí me da un poco igual, así que adelante. Los posibles temas técnicos futuros (balanceo de carga y similar) podrían resolverse llegado el momento.
