### ISSUE TITLE
¿Deberíamos seleccionar la pestaña de nodos al hacer el análisis de redes?

### ISSUE THREAD

**Issue by dcabo** [civio/onodo#284]
He pasado veinte minutos largos dando vueltas como un tonto, pensando que se había (o yo había) roto el análisis de redes, porque no aparecían las nuevas columnas hasta que refrescaba. Por el camino he encontrado un error #283, que estaba convencido era la causa de todo.

Al final me he dado cuenta de que estaba mirando la pestaña de relaciones, no de nodos, así que normal que no viera las nuevas columnas. Grr. Porque creaba una visualización, dos nodos, luego una relación, le daba al botón... 😊 

¿Tiene sentido que cambiemos nosotros la pestaña automáticamente?

**Comment by rauldiazpoblete** [comment]
He añadido una función `updateTable` en `visualization-table-base.js` en https://github.com/civio/onodo/commit/161a1202a18199060852d9f48f4d2dfe7213d392 para hacer un resize de la tabla y volver a renderizarla después de añadirle un `custom_field` (o hacer un Network Analysis). De esta manera se actualiza el scroll de la tabla (apareciendo scroll horizontal en caso de ser necesario) y posicionamos el scroll horizontal a la derecha del todo para que el usuario pueda ver la columna que acaba de añadir. 
También he aprovechado para añadir un poco me margen a la parte inferior de la tabla de edición de manera que no quede tan pegada al final del navegador.
