### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by boogheta** [civio/onodo#293]
Hi,
I cannot find any reference to a license under which this repository is published, neither as a LICENSE file nor in the package.json or the README.
Is this project open source?
If it is, is it under an MIT/Apache/BSD model or a GPL one?

**Comment by dcabo** [comment]
Hi, Benjamin,

We forgot to say it with the last minute rush, but it's AGPL. We just added the license file at 6a70e83596bc0ca360ec4f58bc45125c1ef62bab. Thanks for pointing it out!

**Comment by boogheta** [comment]
Great! Thanks a lot @dcabo & @rauldiazpoblete 
David, will we get a chance to meet again in Paris by the end of the year for the OGP summit?
In any case, you will probably meet @teymour and @fmassot at the OpenData Conference in Madrid early october!

**Comment by dcabo** [comment]
Welcome. ;) We didn't submit a proposal for the OGP summit because we ran out of time, but we're thinking of attending anyway. But a bunch of us Civios will be around in the Madrid conference, so happy to meet @teymour and @fmassot!
