### ISSUE TITLE
Typo in demo steps' descriptions

### ISSUE THREAD

**Issue by dcabo** [civio/onodo#297]
A user mentioned we have the word 'complimentary', when it should be 'complementary'.

**Comment by dcabo** [comment]
@EvaBelmonte: I had missed the demo texts when reviewing the translations. I've done it now, and changed a few other minor things. Are you ok with [the changes](https://github.com/civio/onodo/commit/73575abb8db1b35c0d5315933d00b35ba1a0a608)?

**Comment by EvaBelmonte** [comment]
👍
