### ISSUE TITLE
Add performance tracking tools

### ISSUE THREAD

**Issue by dcabo** [civio/onodo#300]
Adding the free version of NewRelic is simple and gives basic information. I don't know if there's a better alternative these days.

**Comment by esebastian** [comment]
I've created a New Relic Account and configured the APM monitoring. We're getting 14 days of Pro plan and then it will revert to Lite plan (details in https://newrelic.com/application-monitoring/pricing).

**Comment by esebastian** [comment]
New Relic monitoring was added in 1882d9d.
