### ISSUE TITLE
Public access is allowed to visualizations in draft state

### ISSUE THREAD

**Issue by esebastian** [civio/onodo#310]
Is it a bug or a feature?

**Comment by rauldiazpoblete** [comment]
Esto está muy vinculado a lo que comentamos en https://github.com/civio/onodo/issues/121.
Lo hemos dejado así aposta de momento para que alguien pueda compartir la url de una visualización en draft antes de publicarla.
Cierro de momento este issue para no tener temas duplicados.

**Comment by esebastian** [comment]
En una conversación con @dcabo a principios de agosto sobre el `robots.txt` y los crawlers nos surgió la duda de si los drafts eran accesibles o no, y yo afirmé muy rápidamente que no lo eran...  Pero resulta que sí lo son, no sólo a usuarios registrados, sino a todo el mundo en general.

**Comment by rauldiazpoblete** [comment]
Creo que está bien que los drafts sean accesibles pero sólo a usuarios registrados. ¿Estamos de acuerdo en ello? Si es así tendríamos entonces que bloquear el acceso a drafts para usuarios no resitrados.

**Comment by dcabo** [comment]
hmm, no lo tengo claro. Si cerramos el acceso a usuarios no registrados entonces el caso de uso que se supone que queremos facilitar, compartir una visualización no terminada, tampoco funciona muy bien, porque se lo compartirás a gente que no estará registrada.

¿Cual es la solución buena a largo plazo, más allá de los atajos que tomemos ahora? ¿Generar una "URL para compartir", como se hace en otras aplicaciones?

**Comment by rauldiazpoblete** [comment]
Después de debatirlo de nuevo y como no lo vemos claro del todo, de momento creemos que lo mejor es capar los drafts a cualquiera que no sea el autor de la visualización. Más adelante podemos plantear lo que comenta @dcabo de generar una "URL para compartir" para poder enviar a algún colaborador. 
@esebastian , ¿te encargas de bloquear el acceso a los drafts?

**Comment by esebastian** [comment]
Ok. Entonces sin acceso excepto por parte del propietario, aunque sean usuarios registrados.

**Comment by esebastian** [comment]
He implementado los checks para bloquear los accesos en 5ed5645. He tenido que tocar en varios sitios, probad por favor la aplicación en local cuando tengáis un rato antes de que lo subamos a producción, por si en la verificación se me ha pasado algo.
