### ISSUE TITLE
Avoid demo visualization in explore

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/onodo#313]

**Comment by rauldiazpoblete** [comment]
Hay bastantes visualizaciones demo que aparecen en explore (por ejemplo: https://onodo.org/visualizations/3040) y no termino de entender muy bien por qué (en principio las demos no pueden guardarse). 
@esebastian se te ocurre a tí por qué puede suceder esto?

**Comment by esebastian** [comment]
Aparecen en 'Explore' porque las han publicado. De momento voy a despublicarlas desde la consola. Para solucionarlo en el futuro se me ocurre meter una validación en el back para que no se puedan publicar las visualizaciones del usuario 'demo' desde la aplicación, y eliminar la opción del menú en el front.

**Comment by rauldiazpoblete** [comment]
Pero una demo no puede publicarse desde el front porque no mostramos el menú de acciones. Por eso no comprendo cómo han llegado a publicarse estas visualizaciones.

**Comment by esebastian** [comment]
Ya, pero es accesible poniendo la URL de la visualización. Quizá se pueda ver el ID de la visualización en algún momento inspeccionando el HTML o quizá alguien ha ido probando IDs en la URL.

**Comment by esebastian** [comment]
He incluido la comprobación del usuario demo antes de publicar una visualización en 6807aee. Devuelvo un mensaje de error en el `flash`, pero en esa pantalla los mensajes aparecen cortados.
