### ISSUE TITLE
Felicidades

### ISSUE THREAD

**Issue by ToMas-hack** [civio/onodo#360]
Primero de todo felicitaros por el proyecto, me parece espectacular.
Mi consulta..tengo una base de datos en sqlite, y me gustaria poder visualizar las relaciones con Onodo, pero solo domino un poco de python, y no se por donde comenzar..
¿me podéis ayudar a por donde comenzar?
Gracias

**Comment by dcabo** [comment]
Gracias por las felicitaciones.

Onodo ahora mismo no puede conectarse a bases de datos externas para visualizar sus datos. Lo que sí puedes hacer es exportar tus datos de sqlite y ponerlos en el formato de la plantilla Excel que ofrecemos ([ésta](https://github.com/civio/onodo/files/2491558/onodo_template.xlsx)), y subir entonces el Excel a mano para crear el gráfico.

**Comment by ToMas-hack** [comment]
Gracias por tu rápida respuesta.
¿Es posible trabajar en local con ella?

**Comment by dcabo** [comment]
Onodo es código abierto, todo lo que necesitas está en este repositorio, así que puedes instalarte la aplicación web en local. En el `README.md` del repositorio tienes instrucciones.

Es una aplicación en Ruby on Rails que usa Postgres, y ahora hemos añadido soporte para Docker, así que es posible que necesites ciertos conocimientos de estas herramientas. Lamentablemente no podríamos darte soporte, porque somos pocos en Civio y no nos da la vida.

**Comment by ToMas-hack** [comment]
Gracias.!
