### ISSUE TITLE
Request: node size inheritance

### ISSUE THREAD

**Issue by dumbenis** [civio/onodo#368]
When 10 employees are connected to 1 department manager and this department manager is connected to a business director, the node size, based on the number of links, of the department manager will be larger than that of the business director. 
Question: can the business director inherit the number of links of the department manager?

**Comment by dcabo** [comment]
Hi @dumbenis. I'm afraid at the moment you can't do that type of advanced calculation directly in Onodo. But if you create an additional column and fill it with the calculation you describe, you can then set the node size based on that new column. You can either fill it up manually or upload an Excel spreadsheet with it already filled. Hope this helps.
