### ISSUE TITLE
Fix/hide Explore tab

### ISSUE THREAD

**Issue by dcabo** [civio/onodo#370]
Seems like spammers found a new hobby: a user (a teacher from Canada) just alerted us it was full of spam for "Indian call girls". I deleted the spam manually, but I guess more will come, spammers are stubborn like that. Having an unfiltered unmoderated list of "latest visualisations" is risky, and doesn't show the best uses of Onodo anyway, so we should probably hide/remove the tab once we get Onodo moving again. (The Gallery tab is manually curated, that's fine.)

**Comment by dcabo** [comment]
Miguel me ha avisado de que había mucho spam reciente, así que he entrado y he hecho una limpieza de las últimas páginas, [eliminando las cuentas de spam](https://github.com/civio/infra-management/issues/141#issuecomment-704997017).

**Comment by anerodata** [comment]
He eliminado el botón y el enlace que llevaban a la pestaña _explore_ en [`index.html.haml`](https://github.com/civio/onodo/blob/master/app/views/home/index.html.haml) y he eliminado las rutas en [`routes.rb`](https://github.com/civio/onodo/blob/master/config/routes.rb). No estoy seguro de si habría que eliminar también los métodos `explore_visualizations` y `explore_stories` de la clase [`pages_controller.rb`](https://github.com/civio/onodo/blob/master/app/controllers/pages_controller.rb)

**Comment by dcabo** [comment]
@esebastian ¿cómo se despliega Onodo en producción? Estoy intentando hacer memoria. Pensaba que podría entrar en `ramon` y hacer un `git pull` sin más, y pensaba que es lo que había hecho hace un año, cuando arreglé un error puntual (#364), pero al entrar ahora veo que hay una serie de `releases` que no son repos de `git`. ¿Hay algún _script_ de Capistrano o algo similar que me estoy perdiendo?

**Comment by dcabo** [comment]
Ah, claro, sí hay un fichero Capistrano, duh, lo tengo delante. Pero, aparte de que no he usado Capistrano en años, no veo nada para desplegar una nueva versión. Cuando puedas, explícame cómo lo hacías. Gracias!

**Comment by dcabo** [comment]
Justo, sí, la cosa es redesplegar master. El cambio, muy visible, es quitar el enlace a Explore en la portada y barra de navegación, porque está lleno de spam. Así que verás fácil si se ha desplegado bien.

**Comment by dcabo** [comment]
Gracias!!

**Comment by esebastian** [comment]
Esto ya estaría resuelto, así que se podría cerrar si veis que no se necesita nada más.

**Comment by dcabo** [comment]
Estupendo, mil gracias @esebastian, ya he visto que ha dado un poco por saco rescatar esto.

Recuérdame por favor cómo queda la cosa ahora para desplegar con Capistrano. Es el `bundle exec cap production deploy` que mencionabas?

**Comment by esebastian** [comment]
Exacto @dcabo, se despliega con `bundle exec cap production deploy` y lo único que tienes que tener configurado en tu máquina es la _key_ ssh para poder conectar con `ramon`.

Como las versiones de Ruby, Node y las dependencias ya son antiguas, para evitar problemas yo lo he estado haciendo desde Docker:
```
$ docker build . -t civio/onodo:latest
$ docker run -it -v $HOME/.ssh:/root/.ssh civio/onodo bash
# bundle exec cap production deploy
```
